site_name: Cloud-Optimized Geospatial Data Access 
site_url: https://charlottecrevier.github.io/how-to/
repo_url: https://github.com/charlottecrevier/how-to
# repo_name: charlottecrevier/how-to

site_dir: public

docs_dir: .

theme:
  # name: readthedocs
  name: material
  language: en
  features:
  #   - navigation.tabs # Ne fonctionnne pas...
    # - navigation.indexes
    # - navigation.top # Ne marche pas
    # - navigation.footer

# extra: 
#   social: # Ne marche pas
#     - icon: fontawesome/brands/github
#       link: https://github.com/charlottecrevier/how-to

plugins:
  - same-dir
  - search
  - mkdocstrings :
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_options
        # https://mkdocstrings.github.io/griffe/docstrings/#examples_1
        python:
          options:
            docstring_style: numpy
            merge_init_into_class: True
            show_if_no_docstring: true
            # docstring_section_style: table
            # show_docstring_modules : False

markdown_extensions:
  - pymdownx.snippets # THIS IS SICK!!!! https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - attr_list
  - md_in_html
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
  # - pymdownx.inlinehilite
  - pymdownx.superfences # For the colors in the python codeblocks
  # - pymdownx.details
  - admonition
  - pymdownx.emoji

nav:
  - Home : docs/home.md
  # - readme : README.md
  - How-to guides : 
    - Interacting with CCMEO STAC API : docs/pystac-client.md
    # - Interact with COGs
    - Other : docs/index.md
  - References : docs/reference.md
  # - FAQ