name: Pages
on:
  push:
    branches:
        - 7-412-add-a-page 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install mkdocs>=1.1.2
          pip install "mkdocstrings[python]"
          pip install "markdown-exec[ansi]"
          pip install mkdocs-same-dir
      - name: Build site
        run: mkdocs build --strict --verbose
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # upload entire directory
          path: public/
# Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
